Part 1
Baldinini/cinema pull request #1
Opened 2021-01-26 15:45 UTC by Baldinini

2021-01-26 16:50 UTC, vlykhvar requested changes

2021-01-26 16:50 UTC, vlykhvar commented on src/main/java/mate/academy/util/HibernateUtil.java
> +    public HibernateUtil() {
From Checklist "Add a private default constructor to HibernateUtil class in order to prevent HibernateUtil’s objects creating"

2021-01-26 16:54 UTC, vlykhvar approved these changes

2021-01-27 08:01 UTC, Sofasmile requested changes

2021-01-27 08:01 UTC, Sofasmile commented on pom.xml
> +                    <webXml>src/main/webapp/web.xml</webXml>
do we have web.xml?

2021-01-27 08:01 UTC, Sofasmile commented on src/main/java/mate/academy/dao/impl/MovieDaoImpl.java
> +            movie.setId(id);
https://mate-academy.github.io/jv-program-fulltime/03_hibernate/checklist/hibernate_01.html

2021-01-27 09:51 UTC, RomanDubovskyi approved these changes

2021-01-27 09:57 UTC, merged