added Role, CustomUserDetailsService, InjectController
Baldinini/cinema pull request #10
Opened 2021-02-20 16:49 UTC by Baldinini

2021-02-20 18:53 UTC, YuraBondarenko approved these changes

2021-02-22 08:21 UTC, Sofasmile requested changes

2021-02-22 08:21 UTC, Sofasmile commented on src/main/java/mate/academy/controllers/InjectController.java
> +@Controller
better use Component annotation here

2021-02-22 08:21 UTC, Sofasmile commented on src/main/java/mate/academy/model/Role.java
> +        }
do we use this code?

2021-02-22 08:21 UTC, Sofasmile commented on src/main/java/mate/academy/security/AuthenticationServiceImpl.java
> +        user.setPassword(encoder.encode(password));
![image](https://user-images.githubusercontent.com/36365171/108679086-abe9ca80-74f4-11eb-8582-d31b82db85dc.png)

2021-02-22 08:21 UTC, Sofasmile commented on src/main/java/mate/academy/controllers/InjectController.java
> +public class InjectController {
better rename this class to DataInitializer

2021-02-22 08:21 UTC, Sofasmile commented on src/main/java/mate/academy/security/CustomUserDetailsService.java
> +        throw new UsernameNotFoundException("User not found");
```suggestion
        throw new UsernameNotFoundException("User not found: " + email);
```

2021-02-22 08:21 UTC, Sofasmile commented on src/main/java/mate/academy/config/SecurityConfig.java
> +                .antMatchers(HttpMethod.PUT).hasRole("ADMIN")
does it work correctly?

2021-02-22 08:21 UTC, Sofasmile commented on src/main/java/mate/academy/model/User.java
> +    @ManyToMany(fetch = FetchType.EAGER)
is FetchType.EAGER good practice?

2021-02-22 15:26 UTC, Sofasmile approved these changes

2021-02-22 15:26 UTC, Sofasmile commented on src/main/java/mate/academy/controllers/DataInitializer.java
>      private final PasswordEncoder encoder;
let's remove PasswordEncoder from here

2021-02-22 15:40 UTC, merged