added SpringSecurity
Baldinini/cinema pull request #9
Opened 2021-02-17 20:48 UTC by Baldinini

2021-02-17 21:29 UTC, antoniukivan approved these changes

2021-02-18 08:31 UTC, KseniiaMakarova requested changes

2021-02-18 08:31 UTC, KseniiaMakarova commented on src/main/java/mate/academy/annotation/EmailValidationConstrain.java
> +public class EmailValidationConstrain implements ConstraintValidator<EmailValidation, String> {
```suggestion
public class EmailValidator implements ConstraintValidator<EmailValidation, String> {
```

2021-02-18 08:31 UTC, KseniiaMakarova commented on src/main/java/mate/academy/annotation/EmailValidationConstrain.java
> +    }
we can remove this

2021-02-18 08:31 UTC, KseniiaMakarova commented on src/main/java/mate/academy/annotation/PasswordValidationConstrain.java
> +public class PasswordValidationConstrain implements
```suggestion
public class PasswordValidator implements
```

2021-02-18 08:31 UTC, KseniiaMakarova commented on src/main/java/mate/academy/annotation/PasswordValidationConstrain.java
> +
redundant empty line

2021-02-18 08:31 UTC, KseniiaMakarova commented on src/main/java/mate/academy/controllers/CustomGlobalExceptionHandler.java
> +
redundant empty line

2021-02-18 09:36 UTC, KseniiaMakarova approved these changes

2021-02-18 10:01 UTC, merged